[package]
name = "subsurface"
version = "0.1.0"
authors = ["Nitori- <nat1192@gmail.com>"]

[dependencies]
cgmath = "*"
dot_vox = "*"
bitflags = "*"
log = "*"
time = "*"

glutin = "*"
gfx = "*"
gfx_window_glutin = "*"
