[package]
name = "subsurface"
version = "0.1.0"
authors = ["Nitori- <nat1192@gmail.com>"]

[dependencies]
glutin = "*"
cgmath = "*"
dot_vox = "*"

[dependencies.glium]
git = "https://github.com/tomaka/glium.git"
